# Generated by Django 3.2.3 on 2021-05-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('datasource', models.CharField(default='', max_length=20)),
                ('campaign', models.CharField(default='', max_length=100)),
                ('clicks', models.CharField(default='', max_length=10)),
                ('impressions', models.CharField(default='', max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
