# Generated by Django 3.2.3 on 2021-05-18 19:09

import csv
from datetime import datetime

from django.db import migrations, transaction


def evaluate_integer(num):
    if not num.isnumeric():
        return 0
    return int(num, 10)


@transaction.atomic
def create_data_entries(apps, schema_editor):
    Data = apps.get_model("backend", "Data")
    Campaign = apps.get_model("backend", "Campaign")
    campaign_names_list = []
    with open("data.csv") as file:
        rows = csv.reader(file)
        next(rows)

        for row in rows:
            campaign_names_list.append(row[2])
            Data.objects.create(
                date=datetime.strptime(row[0], "%d.%m.%Y").date(),
                datasource=row[1],
                campaign=row[2],
                clicks=evaluate_integer(row[3]),
                impressions=evaluate_integer(row[4]),
            )

    campaign_names_set = set(campaign_names_list)

    for campaign_name in campaign_names_set:
        Campaign.objects.create(name=campaign_name)


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_data_entries, migrations.RunPython.noop),
    ]
