# Generated by Django 3.2.3 on 2021-05-18 19:09

from django.db import migrations
from django.db import transaction
from datetime import datetime
import csv


@transaction.atomic
def create_data_entries(apps, schema_editor):
    Data = apps.get_model("backend", "Data")
    Campaign = apps.get_model("backend", "Campaign")
    campaign_names_list = []
    with open("data.csv") as file:
        rows = csv.reader(file)
        next(rows)

        for row in rows:
            campaign_names_list.append(row[2])
            Data.objects.create(
                date=datetime.strptime(row[0], "%d.%m.%Y").date(),
                datasource=row[1],
                campaign=row[2],
                clicks=row[3],
                impressions=row[4],
            )
    campaign_names_set = set(campaign_names_list)
    for campaign_name in campaign_names_set:
        Campaign.objects.create(name=campaign_name)


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_data_entries, migrations.RunPython.noop),
    ]
