# Generated by Django 3.2.3 on 2021-05-18 19:09

from django.db import migrations
from django.db import transaction
from datetime import datetime
import csv


@transaction.atomic
def create_data_entries(apps, schema_editor):
    DataEntry = apps.get_model("backend", "DataEntry")
    with open("data.csv") as file:
        rows = csv.reader(file)
        next(rows)
        for row in rows:
            DataEntry.objects.create(
                date=datetime.strptime(row[0], "%d.%m.%Y").date(),
                datasource=row[1],
                campaign=row[2],
                clicks=row[3],
                impressions=row[4],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_data_entries, migrations.RunPython.noop),
    ]
